### ISSUE TITLE
Chickens have low chance to drop loot egg

### ISSUE THREAD

**Issue by Jkaano** [Jkaano/CustomGCPlugin#1]
When chickens lay an egg I want a 1-1000 chance of dropping a loot egg. This may cause issues with farms though as you would need to implement an item sorter other wise the chest might get crowded with misc. items

**Comment by TheZoq2** [comment]
It would also make regular items farmable which might be an issue. Perhaps make the dropchance 1-100 but only drop loot eggs if no other chickens are nearby

**Comment by Jkaano** [comment]
How about we have the max distance 10 blocks from any other chicken, while farming would still be doable it would be very large and take up more space than what most people would like

**Comment by TheZoq2** [comment]
Sounds like a plan
